base: &base
    app_id: test-1
    app_secret: test-key
    port: 3000
    service:
        api: 'http://www.baidu.com'

development:
    <<: *base
    app_id: test-1
    app_secret: test-key
    service:
        api: 'http://www.baidu.com'

test:
    app_id: test-1
    app_secret: test-key
    service:
        api: 'http://www.baidu.com'

production:
    app_id: test-1
    app_secret: test-key
    service:
        api: 'http://www.baidu.com'
